version: '3.8'

services:
  django:
    container_name: django
    build: .
    volumes:
      - ./transcendence:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    env_file:
      - .env
    command: gunicorn transcendence.wsgi:application --bind 0.0.0.0:8000
  
  nginx:
    build:
      context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8443:443"
    depends_on:
      - django
    environment:
      - DOMAIN=localhost
