# Generated by Django 5.1 on 2024-08-25 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_two_factor_enabled', models.BooleanField(default=False)),
                ('two_factor_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('app', 'App'), ('none', 'None')], default='none', max_length=5)),
                ('profilePicture', models.ImageField(default='defaults/default_profile.png', upload_to='profile_pictures/')),
                ('bannerPicture', models.ImageField(default='defaults/default_banner.png', upload_to='banner_pictures/')),
                ('language', models.CharField(choices=[('nl', 'Dutch'), ('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ct', 'Cat')], default='en', max_length=2)),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('_two_factor_secret', models.CharField(blank=True, db_column='two_factor_secret', max_length=255, null=True)),
                ('one_time_pass', models.CharField(blank=True, max_length=100, null=True)),
                ('blockedUsers', models.ManyToManyField(blank=True, related_name='blocked_users', to='users.userprofile')),
                ('friendRequests', models.ManyToManyField(blank=True, related_name='friend_requests', to='users.userprofile')),
                ('friends', models.ManyToManyField(blank=True, to='users.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
