# Generated by Django 5.1 on 2024-09-23 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='one_time_pass_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_player2_ai', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField()),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('longest_rally', models.IntegerField()),
                ('typeGame', models.CharField(choices=[('Pickup', 'Pickup Game'), ('Tournament', 'Tournament Game')], default='Pickup', max_length=10)),
                ('raw_data', models.JSONField(default=dict)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamesPlayed', models.IntegerField(default=0)),
                ('gamesWon', models.IntegerField(default=0)),
                ('gamesLost', models.IntegerField(default=0)),
                ('gamesDraw', models.IntegerField(default=0)),
                ('highestWinStreak', models.IntegerField(default=0)),
                ('currentWinStreak', models.IntegerField(default=0)),
                ('tournamentsWon', models.IntegerField(default=0)),
                ('tournamentsSecond', models.IntegerField(default=0)),
                ('tournamentsThird', models.IntegerField(default=0)),
                ('tournamentsPlayed', models.IntegerField(default=0)),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
